### ISSUE TITLE
gss error Issue with three time point samples 

### ISSUE THREAD

**Issue by kanekalla** [jaleesr/TrendCatcher#1]
Hi there,

Thank you for a great package for time series analysis.
I was able to process my samples that had four time points but I was unable to process my samples with three time points. when I run `run_TrendCatcher ` I am getting the following error.

Read count table.
Passed Format Check. Count table is 12 Samples, 8780 Genes
Found 101 low count genes.
Count table format correct, finished loading.
gene-wise dispersion estimates
mean-dispersion relationship
final dispersion estimates
Run TrendCatcher.
  `|                                                                 |   0%Warning in .Internal(gc(verbose, reset, full)) :
  closing unused connection 13 (<-localhost:11350)
Warning in .Internal(gc(verbose, reset, full)) :
  closing unused connection 12 (<-localhost:11350)
Warning in .Internal(gc(verbose, reset, full)) :
  closing unused connection 11 (<-localhost:11350)
Warning in .Internal(gc(verbose, reset, full)) :
  closing unused connection 10 (<-localhost:11350)
Warning in .Internal(gc(verbose, reset, full)) :
  closing unused connection 9 (<-localhost:11350)
Warning in .Internal(gc(verbose, reset, full)) :
  closing unused connection 8 (<-localhost:11350)
Warning in .Internal(gc(verbose, reset, full)) :
  closing unused connection 7 (<-localhost:11350)
Warning in .Internal(gc(verbose, reset, full)) :
  closing unused connection 6 (<-localhost:11350)
Warning in .Internal(gc(verbose, reset, full)) :
  closing unused connection 5 (<-localhost:11350)
Warning in .Internal(gc(verbose, reset, full)) :
  closing unused connection 4 (<-localhost:11350)
Warning in .Internal(gc(verbose, reset, full)) :
  closing unused connection 3 (<-localhost:11350)
  |=================================================================| 100%Timing stopped at: 5.052 1.569 29.84
￼ Show Traceback

Error in { : task 3 failed - "gss error in gssanova: unpenalized terms are linearly dependent"`

I would appreciate if you can point me to where the error is coming from ? Is it something with gss package ?

**Comment by wangxinge** [comment]
Hello Anekallav,
Thank you very much using TrendCatcher. 
This error comes from gss fitting process, it is very likely caused by a gene that has all 0 count through all the time points. Please use rowSums to check which gene has the super low count and remove it from your count table. Then re-run TrendCatcher.

**Comment by kanekalla** [comment]
Hi @wangxinge ,

That is what I thought based on the initial error thrown. But, I tested by removing all the genes with nearly zero counts. To test I made a stringent cutoff and here is the data frame with rowsum info, even then I am oberving the following error.
![Screen Shot 2022-01-22 at 4 25 56 PM](https://user-images.githubusercontent.com/9707250/150657397-583901e1-7614-43c5-a612-6aebeb0cd815.png)

Can you kindly look at it ?

**Comment by wangxinge** [comment]
Dear @kanekalla , I've added a show.verbose option in run_TrendCatcher. If you set it to TRUE, it will print gene name which has been successfully processed by gss package. Check the gene name which failed the fitting and you can remove it from your count table.

**Comment by kanekalla** [comment]
Hi @wangxinge , thanks for adding verbose option, but despite removing the gene its picking the next gene to be error prone although the read counts are highly expressed
<img width="783" alt="Screen Shot 2022-01-29 at 9 47 02 AM" src="https://user-images.githubusercontent.com/9707250/151667509-54418b2c-d945-4562-ab75-129ebe3d2e2c.png">
<img width="905" alt="Screen Shot 2022-01-29 at 9 46 22 AM" src="https://user-images.githubusercontent.com/9707250/151667512-166dcae1-5b3c-447c-b2e0-1c3e43d198d6.png">
<img width="644" alt="Screen Shot 2022-01-29 at 9 49 47 AM" src="https://user-images.githubusercontent.com/9707250/151667515-607969e0-86de-427c-8775-60d138062b1f.png">
.

**Comment by wangxinge** [comment]
Hi @kanekalla, this error is due to your data failed to fitting into the gssanova model, due to the "linearly dependent". This happens very rarely, the error catching version will be updated soon, before that, please manually remove it from your count table.

**Comment by wangxinge** [comment]
Hi @kanekalla, another reason you may keep this error is you set your baseline.t in the main function to default, which is 0. However, in your case, it should be 2.

**Comment by kanekalla** [comment]
Hi @wangxinge , thanks for that , I changed the baseline time point and it worked. I appreciate your help.
