### ISSUE TITLE
"Error reading from connection"

### ISSUE THREAD

**Issue by PetrosRoth** [jaleesr/TrendCatcher#11]
Hi, 

I am working on the analysis of a time-course RNA-seq in wheat and I would love to apply your package to identify expression patterns over time. 

While trying to run TrendCatcher, the job is aborted and I got this error message:

_"Read count table.
Passed Format Check. Count table is 24 Samples, 63351 Genes
Found 1352 low count genes.
Count table format correct, finished loading.
gene-wise dispersion estimates
mean-dispersion relationship
final dispersion estimates
Run TrendCatcher.
  |========                                                                                                                                           |   5%Error in unserialize(socklist[[n]]) : error reading from connection
Timing stopped at: 2.41 0.33 82.64"_

Note that preprocess_TrendCatcher works without any problem. Could it be due to resource limitations (CPU, RAM)? 

When I ran the demo it also worked without any issue.

Any thoughts on that?

**Comment by wangxinge** [comment]
Hi @PetrosRoth, thanks for using TrendCatcher! The error looks like coming from your PC limitation. By default, TrendCatcher will detect your CPUs to run jobs parallel. You can try to set rebose to TRUE, so it will use only 1 CPU to run the job, it will be slow though.
