### ISSUE TITLE
"missing value in parameter"

### ISSUE THREAD

**Issue by elizabeththayer5** [jaleesr/TrendCatcher#2]
Hello!
Thanks so much for creating this package! I'm looking forward to seeing my results after running it successfully. However, I am getting an error after trying to run the main function with my data. The file passes all of the first steps, but fails in the middle of running (60% done) and shoots this message: "Error in { : task 1975 failed - "missing value in parameter". I've looked at the csv and everything looks correct, so I'm wondering what parameter it means? If you could give me some insight into what it wants, I would really appreciate it.
Thanks!

**Comment by wangxinge** [comment]
Hello @elizabeththayer5, 
Thank you for choosing TrendCatcher. I've added a show.verbose option in run_TrendCatcher. If you set it to TRUE, it will print gene name which has been successfully processed by gss package. Check the gene name which cause the iteration stopped. Normally super low count may cause gssanova fitting failure, I suggest to remove the super low counted genes before your run TrendCatcher.

**Comment by elizabeththayer5** [comment]
Thank you! That worked perfectly. It was just one gene that was messing it up.
