### ISSUE TITLE
Raw or normalized microarray data for the analysis

### ISSUE THREAD

**Issue by bugie19** [jaleesr/TrendCatcher#3]
Hi,

your tool is really outstanding. thanks for your handworks.

Can we use raw or normalized microarray data instead of bulk RNAseq for the analysis?  I really appreciate your response.

best regards,

Bugie

**Comment by wangxinge** [comment]
Dear bugie19, 
Thank you for liking TrendCatcher. 
The tool is tailored to analyze RNA-seq count data, for which we adapted the negative binomial distribution. Also, all the simulation datasets used to evaluated the model performance were performed on RNA-seq count data. 
The microarray data follows a different distribution, I don't think it is ideal to run it with TrendCatcher.
