### ISSUE TITLE
The additonal factor along with time course

### ISSUE THREAD

**Issue by MusculusMus** [jaleesr/TrendCatcher#4]
To feed the run_TrendCather function, the column name of the CSV file contains all the time information ("ProjectName_Time_Rep1").

Besides the time factor, My data include genotype information, do you think is it possible to find the genotype effect in the context of time?

**Comment by jaleesr** [comment]
Dear @MusculusMus - our current model is primarily suited for comparing two groups over time, hence Genotype 1 vs Genotype 2 over time, similar to disease group versus healthy group over time. We have been thinking about expanding it to comparing multiple groups (different disease severities, different genotypes, etc) but for now the two genotype dynamic trajectories may be best for you. Thanks for your interest.

**Comment by MusculusMus** [comment]
Hi @jaleesr, thanks for your reply and the information about the Genotype1 vs2. However, after executing all the codes in all your vignettes,  I cannot find any information about how to add another factor. 

Thanks again for you time.

**Comment by MusculusMus** [comment]
@wangxinge, thanks for your reply.

**Comment by jaleesr** [comment]
@MusculusMus  Thank you for pointing this out. We described it in the paper but have not yet created a vignette. We will work on this and add the vignette for the group 1 vs group 2. 

From our TrendCatcher paper:

"Permutation testing for assessing differences between groups over time. After fitting gene expression longitudinal profiles from each severity group with a LOESS smoothing spline, we binned the time variable into 100 time intervals and calculated the observed area ratio between 2 curves within each time interval. Next, we shuffled the severity group label on the gene expression longitudinal profiles and repeated the previous step to calculate the shuffled area ratio for each time interval. We iterated the shuffling step 1000 times. In this way, for each time interval, we calculated the P value using the empirical distribution from the permutation test. This permutation test module in TrendCatcher allows users to assess between group differences of dynamic gene expression pathways in a time interval–dependent manner."

 https://insight.jci.org/articles/view/157255

**Comment by jaleesr** [comment]
Dear @MusculusMus, I've added the new vignette of comparing two curves in the vignette folder, [Compare-Curve-Permutation.Rmd](https://github.com/jaleesr/TrendCatcher/blob/master/vignettes/Compare-Curve-Permutation.Rmd). Please check it out. We can only compare two groups by now, cause comparison among more than two curves is still challenging in the field. Hope the vignette will help! Thank you again for trying TrendCatcher! I'll close the issue now.

**Comment by wangxinge** [comment]
Dear @MusculusMus, I've added the new vignette of comparing two curves in the vignette folder, Compare-Curve-Permutation.Rmd, https://github.com/jaleesr/TrendCatcher/blob/master/vignettes/Compare-Curve-Permutation.Rmd. Please check it out. We can only compare two groups by now, cause comparison among more than two curves is still challenging in the field. Hope the vignette will help! Thank you again for trying TrendCatcher! I'll close the issue now.
