### ISSUE TITLE
Is only count table fitting the format of input?

### ISSUE THREAD

**Issue by jamesbangbang1126** [jaleesr/TrendCatcher#8]
Hi! guys, 
Thank you for your great work.
However, I am a little confused if TPM or FPKM, the kind of transformed expressions, could be the input of the function, ‘run_TrendCatcher’. If not, how could I use TPM or FPKM as input?

Thank u in advance.

**Comment by wangxinge** [comment]
Dear @jamesbangbang1126, thanks for using TrendCatcher! The ideal input for run_TrendCatcher function is the raw count table without batch effect. But if you need normalization or batch effect, you can check the source code of preprocess_TrendCatcher.R. Here we applied CPM normaliztion and ComBat_seq batch correction functions, then converted it back into integers.
