### ISSUE TITLE
task 2080 failed - "missing value in parameter

### ISSUE THREAD

**Issue by m03077yhtnt** [jaleesr/TrendCatcher#9]
Thank you for your great jobs.
I am now writing our paper in which we would like to use TrendCatcher for our longitudinal Bulk RNA-seq data.

The following error output come out once I tried "run_TrendCatcher".
##############################################################
master.list<-run_TrendCatcher(count.table.path = file.path, baseline.t = 0, time.unit = "h", min.low.count = 1, para.core.n = NA, dyn.p.thres = 0.05)
##############################################################
Read count table.
Passed Format Check. Count table is 12 Samples, 60325 Genes
Found 39780 low count genes.
Count table format correct, finished loading.
gene-wise dispersion estimates
mean-dispersion relationship
final dispersion estimates
Run TrendCatcher.
  |===============================================================================| 100%Error in { : task 2080 failed - "missing value in parameter"
Timing stopped at: 21.74 14.07 516.2
##############################################################

I have achieved "run_TrendCatcher" when I used your "example.file.path" (system.file("extdata", "Brain_DemoCountTable.csv", package = "TrendCatcher")).

I would be happy if you could help me solve the issue.

Sincerely,

**Comment by wangxinge** [comment]
Dear @m03077yhtnt, thank you for using TrendCatcher!

This error happened when the **corresponding gene expression values are most 0 at multiple time points.**
There is a show.verbose option in run_TrendCatcher() function. You can set it to TRUE, it will print gene name which has been successfully processed by gss package. Check the gene name which cause the iteration stopped. Normally super low count may cause gssanova fitting failure, I suggest to remove the super low counted genes before your run TrendCatcher.

You can try this first, and if you have multiple low expression genes, maybe it is difficult to remove it manually.
We just added updated a feature to pass out the low count genes, **please re-install the package from our github again**, and  use min.low.count parameter in the function to filter all the low.count genes. 

Please let me know if it helps to solve the problem.

**Comment by m03077yhtnt** [comment]
Thank you so much for your swift response. I am now trying the first potential solution: "show.verbose=TRUE".
As the following, the iteration stopped when it showed "ENSG00000236289".
Which does it mean "ENSG00000236289" is a problematic or the next gene of "ENSG00000236289" is a problematic? 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.......................................
[1] "ENSG00000079785"
[1] "ENSG00000233718"
[1] "ENSG00000134323"
[1] "ENSG00000236289"
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
I really appreciate your help.

**Comment by wangxinge** [comment]
I think is the ENSG00000236289" is a problematic (based on memory of the code), but you can check both gene expression count, and manually remove it.
To re-install from github, just do remove.packages("TrendCatcher") and reinstall from our github.

**Comment by m03077yhtnt** [comment]
Just a week ago, I have installed TrendCatcher.
In this case, do I need to reinstall it?

**Comment by wangxinge** [comment]
Yes, please. We just updated today.

**Comment by m03077yhtnt** [comment]
Finally, I have achieved to finish "run_TrendCatcher".
I manually removed the genes which the "show.verbose" function found as there were many genes to stop "run_TrendCatcher" command even though I have reinstalled the package.
Thank you so much for your support.
